[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pypassmgr"
version = "0.0.1"
authors = [{name = "Aaron M.", email = "aaronm6@gmail.com"},]
license = "GPL-3.0"
readme = "README.md"
description = "Simple command-line encrypted password/secret manager"
dependencies = ["cryptography>=42.0.5","urwid<=2.1.2","pyrandomart>=1.0.0"]
classifiers = ["Programming Language :: Python :: 3",]

[project.scripts]
pwpass = "pypassmgr:main"
pw_load_backup = "pypassmgr.convertPWfile:main"

[tool.setuptools]
package-dir = {"" = "."}

#[tool.setuptools]
#py-modules = ["pw_manager_inst","urwid_routines","randomart"]
